# Generated by Django 4.2.2 on 2023-10-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_value',
            field=models.IntegerField(null=True),
        ),
    ]
